TnSolutions_ContratoLocacao/ContratoLocacao.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContratoLocacao.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

TnSolutions_ContratoLocacao/ContratoLocacao.Web/Controllers/RPTContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using System.Data;

namespace ContratoLocacao.Web.Controllers
{
    public class RPTContratoController : Controller
    {
        // GET: RPTContrato
        public ActionResult ImpressaoContrato()
        {
            var ds = Reports.Data.DsImpressaoContrato.ObterRelatorio();


            var viewer = new Microsoft.Reporting.WebForms.ReportViewer();

            //viewer.ProcessingMode = Microsoft.Reporting.WebForms.ProcessingMode.Local;
            viewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Reports\Rpt\Rpt_ImpressaoContrato.rdlc";
            viewer.LocalReport.DataSources.Add(new Microsoft.Reporting.WebForms.ReportDataSource("dsDetalhe1", (System.Data.DataTable) ds.PR_IMPRESSAO_CONTRATO));
            
            


            viewer.SizeToReportContent = true;
            viewer.Width = System.Web.UI.WebControls.Unit.Percentage(100);
            viewer.Height = System.Web.UI.WebControls.Unit.Percentage(100);

            
            ViewBag.ReportViewer = viewer;
            return View();
        }
    }
}

TnSolutions_ContratoLocacao/ContratoLocacao.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<br />
<br />
<a class="btn btn-success" @Html.ActionLink("Incluir novo contrato", "NovoContrato", "Contrato")<span class="sr-only">(current)</span></a>
<br />
<br />
<a class="btn btn-primary" @Html.ActionLink("Lista de contratos", "ListaContratos", "Contrato")<span class="sr-only">(current)</span></a>
<br />
<br />
<a class="btn btn-danger" @Html.ActionLink("Impressão Contrato", "ImpressaoContrato", "RPTContrato")<span class="sr-only">(current)</span></a>

@*<br/>

        @Html.ActionLink("Cadastro Locatário", "NovoLocatario", "Locatario")

    <br/>

        @Html.ActionLink("Cadastro Locador", "NovoLocador", "Locador")*@